driver=com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
url=jdbc:mysql://localhost:3306/lms_db
user=root
password=4632
=======
url=jdbc:mysql://localhost:3306/fairy_lms
user=fairy
password=fairy
>>>>>>> 982c395846594eaed673f4dbcbcdd294c243317b
